# Generated by Django 4.1.13 on 2024-05-15 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorFullData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('source', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('fps', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
