# Generated by Django 4.1.13 on 2024-08-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0002_sensorfulldata_sensor_created_at_sensor_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('component_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
